### ISSUE TITLE
it is not rendering query parameters

### ISSUE THREAD

**Issue by ilearnbydoing** [phprouter/router_xss_csrf#10]
oai?verb=ListIdentifiers&metadataPrefix=oai_dc

not working

**Comment by phprouter** [comment]
What is not working, specify the issue?

**Comment by zerofinding** [comment]
http://localhost:8090/item/macbook?price=1100&qty=7&type=&color=black

var_dump($parameters);
var_dump($querystrings);
var_dump($name);
var_dump($price);
var_dump($qty);
var_dump($type);
var_dump($color);

router.php
[router.php.txt](https://github.com/phprouter/main/files/7473097/router.php.txt)

**Comment by phprouter** [comment]
PhpRouter does not overwrite the normal PHP behaiviour. To retrieve varaibles in the query string you must use the normal $_GET. If you want to access variables from a form, then you use $_POST
