### ISSUE TITLE
How to force HTTPS?

### ISSUE THREAD

**Issue by liagason** [phprouter/router_xss_csrf#11]
Hi, I have included router.php and routes.php in a "src" folder outside htdocs and I have included only index.php in my htdocs folder.

In the index.php file I have the following code:
 `require_once("../src/routes.php");`

Everything seems to work right (secure connection) when I type https://localhost, but not when I type http://localhost or localhost. Here is my .htaccess file:
```
RewriteEngine On

RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}

RewriteCond %{REQUEST_URI} !(\.png|\.jpg|\.gif|\.jpeg|\.zip|\.css|\.svg|\.js)$
RewriteRule (.*) index.php [QSA,L]
```

Any tips on what might be the problem?

**Comment by liagason** [comment]
Nevermind. Fixed it.
```
RewriteEngine On

RewriteCond %{HTTPS} !=on
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301,NE]

RewriteCond %{REQUEST_URI} !(\.png|\.jpg|\.gif|\.jpeg|\.zip|\.css|\.svg|\.js)$
RewriteRule (.*) index.php [QSA,L]
```

**Comment by phprouter** [comment]
You could also add HTTPS at the server level and not by using the .htaccess file.

**Comment by gubi** [comment]
Add this to the .htaccess file:
```
# Redirect to https
RewriteCond %{HTTPS} !on
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
```
