### ISSUE TITLE
How to pass query parameters to the path_to_include

### ISSUE THREAD

**Issue by lcsqlpete** [phprouter/router_xss_csrf#13]
Really like this library which will save me a lot of work.

The docs seem to discourage the use of query parameters but it's not uncommon for APIs to have query parameters as allowed by the OpenAPI spec. However it looks like they aren't made available to the path_to_include, meaning $_GET is empty.

I can easily edit the code to parse the query parameters into a $_GET array but wanted to check I'm not missing something before doing that.

**Comment by phprouter** [comment]
You are passing query parameter fine. Keep on using $_GET to access them.
