### ISSUE TITLE
Pagination in phprouter App

### ISSUE THREAD

**Issue by Chinedumeze** [phprouter/router_xss_csrf#14]
Please has anyone using this Library - phprouter, been able to successfully implement a Search Result Pagination?

Please, if you have, kindly share it with me. I just am not able to get it to work ! Or, am I trying the impossible? Is this Router not designed to handle Paginations?
Urgent help will be highly appreciated. 

Adolf

**Comment by malouf-dev** [comment]
Pagination with GET variables:
`test.com/blogs?page=1`
Or with the url:
`test.com/blogs/1`
?

**Comment by Chinedumeze** [comment]
Thank you very much for your kindness, sir.

Then, please see if the following are correct:

1) <form action="/search" method="get" >...</form >;


2) Route - get('/search/page/$page', 'views/search.php');


And, pagination links like:

3) <a href='search?page="$page">$page</a>


Please also concerning the route, should there be a second route also
pointing to the same search.php page, like,

Route 2 - get('/search', 'views/search.php');


Best regards


Ezeribe Adolf

**Comment by phprouter** [comment]
It does support pagination. Use a get request passing the page id as the variable:

get('/items/$page_id', 'views/items');

**Comment by phprouter** [comment]
Pagination is possible. Read my reply

**Comment by Chinedumeze** [comment]
Dear sir,
I am truly sorry to be troubling you! Please accept my regrets and
apologies.

I have read your reply and tried to work with it. See what I did. I must
have failed with something and it is not working! Help me pinpoint what I
have done wrong:
1) The Routes:
     get('/search', 'views/search.php');
     get('/search/page/$p', 'views/search.php');
     post('/search', 'views/search.php');
     post('/search/page/$p', 'views/search.php');

2) The Form:
     (i) <form class="search__form" action="/search" method="post">
     (ii) <form class="search__form" action="/search" method="get">
3) The pagination link:
echo "
<li class='paginate__item'><a class='paginate__link' href='/search?page=$
second_last'>$second_last</a></li>";
echo "
<li class='paginate__item'><a class='paginate__link' href='/search?page=$
pages'>$pages</a></li>";

Please help point out my mistakes, please. Thank you very much for your
great help.


*Ezeribe, A. C.*


*Phone: +234 803 713 3024; *

*             +1-574-807-9900email:  ***@***.*** ***@***.***>*

*Taste & See that Yahuwah, our Almighty Elohim is good.*
