### ISSUE TITLE
Global variables doesnt work

### ISSUE THREAD

**Issue by segovialucio** [phprouter/router_xss_csrf#16]
Hi, i dont know what happend but when i use routing, i cant use global variables. If i dump $GLOBALS, they doesnt show

**Comment by phprouter** [comment]
It does work

**Comment by harrisonratcliffe** [comment]
I am also having issues with global variables. Can you show code as an example that it works @phprouter ?
**Code:**
```
$testVar = "testing";

function globVar() {
    global $testVar;
    echo $testVar;
}

globVar(); 
```
**Output of `var_dump($GLOBALS['testVar']);`:**
`NULL`
