### ISSUE TITLE
Page isn't working

### ISSUE THREAD

**Issue by menjilx** [phprouter/router_xss_csrf#18]
I tried to customize the folder structure but I got this "Page isn't working" error.
Here's my folder structures, htaccess, and index code file.
![image](https://user-images.githubusercontent.com/14908836/145575834-98d0d0b9-6619-4328-8f40-4b3bf77345e9.png)

**index.php**
`<?php
// include router php file
require_once 'routes/routes.php';`

**.htaccess**
`RewriteEngine On
RewriteCond %{REQUEST_URI}  !(\.png|\.jpg|\.gif|\.jpeg|\.zip|\.css|\.svg|\.js)$

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f

RewriteRule ^(.+)$ index.php/$1 [L]`

**Comment by phprouter** [comment]
The files "router.php" and "routes.php" should be under the root directory
