### ISSUE TITLE
Not working in Nginx

### ISSUE THREAD

**Issue by tierdogan** [phprouter/router_xss_csrf#23]
Unfortunately not working in Nginx. Only a blank white page appears. Why can it be caused? No problem with rewrites.

**Comment by phprouter** [comment]
Did you find a solution to it?

**Comment by EtskaCoding** [comment]
I have working nginx configuration, it's attached below.

[default.conf.txt](https://github.com/phprouter/main/files/8710946/default.conf.txt)

**Comment by Tokyo-Lei** [comment]
How to write the controller? 

get(  '/index' ,  'views/indexcontroller@index'  );

**Comment by Orio-nn** [comment]
This is (probably) caused by NGINX not supporting `.htaccess` files. `.htaccess` files are native to apache so this repository (assumedly) wont work out of the box on an NGINX server.

If you're on an NGINX server I would test the file below.

> I have working nginx configuration, it's attached below.
> 
> [default.conf.txt](https://github.com/phprouter/main/files/8710946/default.conf.txt)

**Comment by phprouter** [comment]
Thank you for helping with the nginx issue
