### ISSUE TITLE
Problems with callbacks functions

### ISSUE THREAD

**Issue by BloberSh** [phprouter/router_xss_csrf#24]
Hello, 

I started using the callback functions (which are an awesome add) but I have a problem with it.

Even when using different urls, only the first one is always used (also if I try to go to /admin, it redirect to /)
If I comment the login header redirection, there is just no redirections at all (even on logout and `session_unset()` is not ran)

```php
get('/', 'app/index/index.php');


get('/user/login', function(){
    $_SESSION['logged'] = true;
    header('Location: /');
});

get('/user/logout', function(){
    session_unset();
    header('Location: /');
});

get('/admin', 'app/admin/index.php');
```

Any idea why this happen?

EDIT : I added the test callback (the same one as website show) before the login callback and when I go to `/user/logout`, it just show `Awesome`.

**Comment by santiagodonoso** [comment]
I have updated the code. Multiple callbacks and multiple routes should work now.

**Comment by phprouter** [comment]
Updated router.php. Now it is possible to have multiple routes and multiple callbacks.
