### ISSUE TITLE
Problem with src and href

### ISSUE THREAD

**Issue by AlonsoCauich** [phprouter/router_xss_csrf#26]
Al momento de añadir un archivo css o script en el archivo php, lo bloque y no deja acceder al archivo local del proyecto, me puedes ayudar?

###
When adding a css or script file in the php file, it blocks it and does not allow access to the local project file, can you help me?

**Comment by AlonsoCauich** [comment]
cuando añado un archivo script marca el error, y el contenido del archivo solo muestra el error 404
Uncaught SyntaxError: Unexpected token '<' (at result.js:1:1)

**Comment by VRXT** [comment]
Hello, @AlonsoCauich 

The File ".htaccess" lets you pass through the router so you need to make sure you have a valid path 

![image](https://user-images.githubusercontent.com/25876547/174947538-a1e0b6fd-38e2-4a40-a6b1-d07fa126e6f2.png)

you can fix this by creating a folder "assets" on the root path

![image](https://user-images.githubusercontent.com/25876547/174947436-80ac632f-8389-499d-a13f-c289d5d8d523.png)

 **OR**

You can use Define a content delivery network (CDN)

![image](https://user-images.githubusercontent.com/25876547/174948238-41475933-db35-4e67-a672-bcd0125c23b5.png)

And add it to your code 

![image](https://user-images.githubusercontent.com/25876547/174948427-ede90000-820b-4a3b-b32f-6e0a3e38fbbc.png)

**Comment by AlonsoCauich** [comment]
> Hello, @AlonsoCauich
> 
> The File ".htaccess" lets you pass through the router so you need to make sure you have a valid path
> 
> ![image](https://user-images.githubusercontent.com/25876547/174947538-a1e0b6fd-38e2-4a40-a6b1-d07fa126e6f2.png)
> 
> you can fix this by creating a folder "assets" on the root path
> 
> ![image](https://user-images.githubusercontent.com/25876547/174947436-80ac632f-8389-499d-a13f-c289d5d8d523.png)
> 
> **OR**
> 
> You can use Define a content delivery network (CDN)
> 
> ![image](https://user-images.githubusercontent.com/25876547/174948238-41475933-db35-4e67-a672-bcd0125c23b5.png)
> 
> And add it to your code
> 
> ![image](https://user-images.githubusercontent.com/25876547/174948427-ede90000-820b-4a3b-b32f-6e0a3e38fbbc.png)

Hello @VRXT 

In which file should I define the content delivery network (CDN)? router.php or routes.php?

En qué archivo debo definir la red de entrega de contenido (CDN)? router.php or routes.php?

**Comment by VRXT** [comment]
hello @AlonsoCauich 

You can put it where you like, I recommends to put it in new file (settings.php) and require_ones in routes.php
