### ISSUE TITLE
How do I add absolute paths?

### ISSUE THREAD

**Issue by ghost** [phprouter/router_xss_csrf#27]
How do I add absolute paths so that I can identify the images and files inside the public folder, where they contain the CSS, JS and img?

**Comment by VRXT** [comment]
Hello, @stevenhau 

The File ".htaccess" lets you pass through the router so you need to make sure you have a valid path 

![image](https://user-images.githubusercontent.com/25876547/174947538-a1e0b6fd-38e2-4a40-a6b1-d07fa126e6f2.png)

you can fix this by creating a folder "assets" on the root path

![image](https://user-images.githubusercontent.com/25876547/174947436-80ac632f-8389-499d-a13f-c289d5d8d523.png)

![image](https://user-images.githubusercontent.com/25876547/174950370-9209eb7d-4008-4f3f-88d8-b712c75d68b4.png)

Is this what you mean?

**Comment by phprouter** [comment]
The .htaccess file allows direct access to static files like .js and .css
