### ISSUE TITLE
How to use dynamic routes.

### ISSUE THREAD

**Issue by Alonso-Cauich** [phprouter/router_xss_csrf#28]
How do I retrieve the value in the file?.

Example
STANDARD-URL:  item.php?size=10

In the file php, I can print them like this.
<?php
print_r($_GET);  // for all GET variables
?>

DYNAMIC-URL:  get('/item/size/$size', 'views/item.php');
¿How can I see the value now?

---
¿Cómo recupero el valor en el archivo?

Ejemplo
URL ESTÁNDAR: item.php?size=10
En el archivo php, puedo imprimirlos así.
<?php
print_r($_GET); // para todas las variables GET
?>

URL DINÁMICA: get('/item/size/$size', 'views/item.php');
¿Cómo puedo ver el valor ahora?

**Comment by VRXT** [comment]
Hello @Alonso-Cauich it’s become variable

example

<php?
echo $size;
?>

**Comment by Alonso-Cauich** [comment]
@VRXT  Thanks :)
