### ISSUE TITLE
Callback issue

### ISSUE THREAD

**Issue by Orio-nn** [phprouter/router_xss_csrf#31]
When creating a function callback with the link below it throws an error
```php
get('/', function() {
	echo "test";
});
```
However, if you change the link to literally anything else, it will work. This issue seems to only be present on `/` link.
The error message created is attached below.
```
Fatal error: Uncaught Error: Object of class Closure could not be converted to string in C:\xampp\htdocs\rbc\router.php:38 Stack trace: #0 C:\xampp\htdocs\rbc\router.php(6): route('/', Object(Closure)) #1 C:\xampp\htdocs\rbc\routes.php(14): get('/', Object(Closure)) #2 {main} thrown in C:\xampp\htdocs\rbc\router.php on line 38
```

This issue was tested with a brand new clone of this repo.

**Comment by phprouter** [comment]
Callbacks are not intended to be used on the "/" route
