### ISSUE TITLE
Callback on dynamic route

### ISSUE THREAD

**Issue by Orio-nn** [phprouter/router_xss_csrf#33]
Callbacks don't pass the parameters in a dynamic route. Don't know if this is a bug or an unimplemented feature, either way it is an issue.
Take the snippet below (crudely written, apologize for any syntax errors)
```php
get('/user/$user' function($id) {
    // your code here n stuff
});
```

**Comment by phprouter** [comment]
This has been fixed. Now this works:

get('/callback/$name', function($name){
  echo "Callback executed. The name is $name";
});
