### ISSUE TITLE
Subfolder not working

### ISSUE THREAD

**Issue by LethalIndustry** [phprouter/router_xss_csrf#36]
Im having problems in putting my code with routing in a sub folder of wamp, www/urls

does any one have the same problem? I add $ROOT = $_SERVER['DOCUMENT_ROOT']."/urls"; and it loads the index but i try to access -> href="product/shoes/color/blue">Products</a and the url just increments the params like http://localhost/urls/product/shoes/color/product/shoes/color/blue and so on..

**Comment by hawkhxf2000** [comment]
I have the same problem

**Comment by LethalIndustry** [comment]
I dont know if it is the best solution but making test in router.php i made this change
if( @$route_parts[1] == '' && count($request_url_parts) == 1 )

and in routes i added get($FOLDER.'/producto/$type/color/$color', 'producto.php');

**Comment by phprouter** [comment]
The project must be placed and created under the root directory of the Apache server. In some computers this is the "htdocs" folder, or "www" folder.
