### ISSUE TITLE
.htaccess ignores woff files

### ISSUE THREAD

**Issue by andreasdem** [phprouter/router_xss_csrf#37]
I am loading fonts from my assets but i noticed that they were not being loaded.

Then realized that the `.htaccess`  has the following line
`RewriteCond %{REQUEST_URI}  !(\.png|\.jpg|\.webp|\.gif|\.jpeg|\.zip|\.css|\.svg|\.js)$`
which is very limited in terms of files.

My proposed solution is below.
I also added some commets for how to use redirections as I happened to need them in my project!

🍻

```
RewriteEngine On

# You can also user redirections

# Using RewriteBase is particularly useful to avoid typing the folder name in each RewriteRule
# RewriteBase /folder/

# Make sure you don't add a / before new/path for the RewriteBase to take effect
# RewriteRule ^/?path/?$ new/path [R=301,L]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule (.*) routes.php [QSA,L]
```

**Comment by andreasdem** [comment]
<strike>ah... i just realized that this wont work as this also ignores php files 😅 </strike>
<strike>i'll investigate and revert.</strike>
Scratch the above. Everything is working as expected. The issue I had was unrelated to this! 
Thanks for the great work btw! 🙏

**Comment by Orio-nn** [comment]
...Why not just add
`RewriteCond %{REQUEST_URI} !(\.png|\.jpg|\.webp|\.gif|\.jpeg|\.zip|\.css|\.svg|\.js\.woff)$`

**Comment by andreasdem** [comment]
Cause you don't know what other files you might encounter. 
Fonts alone have `eot woff2 woff ttf`

**Comment by Orio-nn** [comment]
> Cause you don't know what other files you might encounter. Fonts alone have `eot woff2 woff ttf`

Fair enough

**Comment by LethalIndustry** [comment]
does any one know how to put my code into a sub folder? like https://domain.com/urls

**Comment by phprouter** [comment]
Hi,

I think you can add woff to the line... so it will end up looking like this:

RewriteCond %{REQUEST_URI} !(\.png|\.jpg|*\.woff*
|\.webp|\.gif|\.jpeg|\.zip|\.css|\.svg|\.js)$

**Comment by phprouter** [comment]
Any special file extension can be added in the .htaccess file.
RewriteCond %{REQUEST_URI}  !(\.png|\.jpg|\.webp|\.gif|\.jpeg|\.zip|\.css|\.svg|\.js)$
