### ISSUE TITLE
MAMP not working?

### ISSUE THREAD

**Issue by kingozorg** [phprouter/router_xss_csrf#39]
Hi! Trying to get this to work on MAMP / Mac Os. Unfortunately I only get the 404 page displayed, no matter which route I use. Also "/" to the index page does not work. What am I doing wrong? Cheers!

**Comment by kingozorg** [comment]
Hi! Seems to work only directly in the root dir of MAMP. So it works great - but not inside a project dir.

**Comment by phprouter** [comment]
All your project, together with PhpRouter must be under the root directory of your server or domain.
