### ISSUE TITLE
How can I route all requests to my single-page application?

### ISSUE THREAD

**Issue by ciromdrs** [phprouter/router_xss_csrf#41]
Hi

I have a REST API written in PHP and a single-page application written in Elm.
How can I make all requests starting with `/api/*` go to their corresponding script in the backend and let everything else go to the frontend (WITH the url preserved)?

I tried this, but it didn't work. 
```
get('/api/foo', 'api/foo.php');
get('/api/bar', 'api/bar.php');

get('/*', 'website/index.html');
```
I can access the API properly at `/api/*`, and the index page at `/`.
However, any other URL will return a blank page, whereas it should return the index page and the single-page application would take care of rendering the corresponding content or a 404 page.

Ps.:
Here's my .htaccess file:
```
RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-l

RewriteRule (.*) routes.php [QSA,L]
```

**Comment by ciromdrs** [comment]
Apparently this works in `.htaccess`:
```
RewriteEngine On

RewriteRule ^api/.*$ routes.php [QSA,L]

FallbackResource index.html
```

and `routes.php`:
```
<?php

require_once __DIR__.'/router.php';

get('/api/foo', 'api/foo.php');
post('/api/bar', 'api/bar.php');

any('/404', '404.php');
```

The `index.html` page renders 404 Not Found pages, whereas the `404.php` script returns a REST 404 message.

**Comment by phprouter** [comment]
If you want to re-direct everything to another page, then use the .htaccess directly. No need to use the router in this situation.
