### ISSUE TITLE
Using phprouter for project in subdirectory 

### ISSUE THREAD

**Issue by GiacomoPope** [phprouter/router_xss_csrf#42]
Hi,

If I have a project in

example.com/new_project

and I want to do routing (e.g.)

example.com/new_project/user/name => example.com/new_project/user.php?name=name

Do I need to change the code? I can't seem to get it working, all I get is blank html when I do the static routing.

**Comment by madanielecd** [comment]
Hi Jack,

You could try this.
1. Place all the phprouter files _(so also the .htaccess file)_ in your subfolder
2. Edit the router.php file accordingly:

**_comment out this line_**
// $request_url = filter_var($_SERVER['REQUEST_URI'], FILTER_SANITIZE_URL);

**_replace it with_**
// start add
$thisPart    = explode(basename(getcwd()), $_SERVER['REQUEST_URI']);
$fromSubBase = (isset($thisPart[1])) ? $thisPart[1] : $thisPart[0];
$request_url = filter_var($fromSubBase, FILTER_SANITIZE_URL); 
// end add

**Comment by phprouter** [comment]
Hi @madanielecd, I have tried your solution to make it part of the router, though it does not work. Can you please let me know how you expect this to be used?

**Comment by madanielecd** [comment]
Hi @phprouter,

Well I'm not sure, but could it be server config dependant? Is your (Apache) server not responding to the .htaccess in a subfolder? 
And fe on nginx it won't work because there is no .htaccess support.

**Comment by phprouter** [comment]
Maybe this works:

<?php
require_once __DIR__.'/router.php';

$basePath='/app';
get("$basePath/", 'views/index.php');
get("$basePath/page1", 'views/page1.php');
any("$basePath/404", 'views/404.php');

**Comment by phprouter** [comment]
PhpRouter is intended to be used directly under the root/domain folder.
