### ISSUE TITLE
HTACCESS Error

### ISSUE THREAD

**Issue by leojarina** [phprouter/router_xss_csrf#43]
I uploaded my entire files on my server and it appears to have some htaccess issues. It displays HTTP Error 500. When I tried to rename the htaccess, it works just fine. Can you help?

Thanks,
Leo

**Comment by phprouter** [comment]
Rename the htaccess? Are you placing it under the root folder of your domain? In localhost, the root folder is usually "htdocs"

**Comment by phprouter** [comment]
Waiting to hear from you
