### ISSUE TITLE
File does not work in subfolders.

### ISSUE THREAD

**Issue by RenanPiresMattos** [phprouter/router_xss_csrf#44]
Hello, currently it only works if you put it in the htdocs folder, is there any way to work in subfolders?

**Comment by madanielecd** [comment]
Hi RenanPiresMattos,

I had the same. You could try this, it worked for me ...

1. Place all the phprouter files _(so also the .htaccess file)_ in your subfolder
2. Edit the router.php file accordingly:

**_comment out this line_**
// $request_url = filter_var($_SERVER['REQUEST_URI'], FILTER_SANITIZE_URL);

**_replace it with_**
// start add
$thisPart    = explode(basename(getcwd()), $_SERVER['REQUEST_URI']);
$fromSubBase = (isset($thisPart[1])) ? $thisPart[1] : $thisPart[0];
$request_url = filter_var($fromSubBase, FILTER_SANITIZE_URL); 
// end add

Hope this works for you also.

**Comment by cancastilho** [comment]
Another way is just putting a basepath var or constant inside routes.php or inside router.php:

In routes.php it would be the following:

```
<?php
require_once __DIR__.'/router.php';

$basePath='/app';
get("$basePath/", 'views/index.php');
get("$basePath/page1", 'views/page1.php');
any("$basePath/404", 'views/404.php');
```

But, it would be better placed inside router.php, to prevent writing '$basePath' many times.

There are some frameworks and libs that have configuration for setting the basePath. It would be nice to have something similar here.

**Comment by phprouter** [comment]
I am still trying to get PhpRouter to work under any subfolder... any good idea, so it will work without having to set variables or configure anything? So, a piece of code that just does the job?

**Comment by BetoMonster** [comment]
Hi,
Based on your comments, I have another solution:

comment out this line
**// $request_url = filter_var($_SERVER['REQUEST_URI'], FILTER_SANITIZE_URL);**

then add these lines to get the subdirectory and separate it from the real request_url
**$api_root=str_replace($_SERVER['DOCUMENT_ROOT'],'',getcwd());
$request_url =str_replace($api_root,'',filter_var($_SERVER['REQUEST_URI'], FILTER_SANITIZE_URL));**

**Comment by Jeroen1979-NL** [comment]
I've added the following line to .htaccess that is placed in the subfolder.

RewriteBase /name_subfolder/

For me it worked with XAMPP on Mac

**Comment by phprouter** [comment]
I have not tested @cancastilho solution, but it makes sence. Use it.

**Comment by CaffeineLab** [comment]
My 2 cents:

I've loaded into a folder called API so I strip out anything after it.   Works well enough so long as 'api' only occurs in the url once.

`
$request_url = filter_var($_SERVER['REQUEST_URI'], FILTER_SANITIZE_URL);

$request_url = substr($request_url, strpos($request_url, "api") + 3);
`

**Comment by phprouter** [comment]
Works under the root folder
