### ISSUE TITLE
Files downloading from page driven by PHP router.

### ISSUE THREAD

**Issue by mediaprofile** [phprouter/router_xss_csrf#45]
I'm trying to use PHP Router in my app, and the problem is when I call the .pdf file to download.
Here is an example code

`<a href=„media/pdfs/file.pdf">FILE</a> `

The router goes to the 404 page. 
Could you advise any solution?

Thanks

**Comment by andrewski04** [comment]
The default htaccess file causes requests for pdf files to be directed to the router. Update your htaccess to remove rewrites for pdf files.


`RewriteEngine On`
`RewriteCond %{REQUEST_URI}  !(\.png|\.jpg|\.webp|\.gif|\.jpeg|\.zip|\.css|\.svg|\.js|\.pdf)$`
`RewriteRule (.*) routes.php [QSA,L]`

**Comment by mediaprofile** [comment]
Yes, It's obvious. It works perfectly.
ThX
