### ISSUE TITLE
group

### ISSUE THREAD

**Issue by OrPh4ns** [phprouter/router_xss_csrf#50]
Can you create a function to make a groupt of routers?

like 

profile/show
profile/get
profile/edit
...
.
.

**Comment by KonradWebArray** [comment]
You want all those routes to share the same action? I'm not sure why you would want to do that as it will just make your code harder to follow, but if you want to do it like this then just change all the get, post, put, patch, delete functions to accept an array for the route, convert non array values to an array and loop though each route. Here's an example to get you started.

private function set($method, $route, $action) {
	if (!is_array($route))
		$route = [$route];
	foreach ($route as $r)
		$this->routes[$method][$r] = $action;
}

public function get($route, $action) {
	$this->set('GET', $route, $action);
}

public function post($route, $action) {
	$this->set('POST', $route, $action);
}

public function put($route, $action) {
	$this->set('PUT', $route, $action);
}

public function patch($route, $action) {
	$this->set('PATCH', $route, $action);
}

**Comment by KonradWebArray** [comment]
You want all those routes to share the same action? I'm not sure why you would want to do that as it will just make your code harder to follow, but here you go:

```
private function set($method, $route, $action) {
     if (!is_array($route))
          $route = [$route];
     foreach ($route as $r)
          $this->routes[$method][$r] = $action;
}

public function get($route, $action) {
     $this->set('GET', $route, $action);
}

public function post($route, $action) {
     $this->set('POST', $route, $action);
}

public function put($route, $action) {
     $this->set('PUT', $route, $action);
}

public function patch($route, $action) {
     $this->set('PATCH', $route, $action);
}

public function delete($route, $action) {
     $this->set('DELETE', $route, $action);
}

public function any($route, $action) {
     $this->set('GET', $route, $action);
     $this->set('POST', $route, $action);
     $this->set('PUT', $route, $action);
     $this->set('PATCH', $route, $action);
     $this->set('DELETE', $route, $action);
}
```

Now you can either specify a single route:
`$Router->get('/example', 'views/example.php');`

Or you can specify many:
```
$Router->get(
     [
          '/example',
          '/another-example',
          '/home/example',
          '/dynamic/$example'
     ],
     'views/example.php'
);
```
