### ISSUE TITLE
post method not working

### ISSUE THREAD

**Issue by ghost** [phprouter/router_xss_csrf#51]
post('/login', 'controllers/LoginController.php');

<form method="POST" class="panel__login__form">
                    <input type="text" name="email" placeholder="Podaj email">
                    <input type="password" name="password" placeholder="Podaj hasło">
                    <input type="submit" value="Zaloguj się" name="submit">
                    </form>
                
                when i submit form i see this any('/404','views/404.php');
                
                .htacces file:
                
                Options +FollowSymLinks
                RewriteEngine On
                RewriteCond %{REQUEST_FILENAME} !-f
                RewriteCond %{REQUEST_FILENAME} !-d
                RewriteCond %{REQUEST_METHOD} ^(POST)
                RewriteRule ^(.*)$ index.php?url=$1 [QSA,L]

**Comment by phprouter** [comment]
I just added a new route as an example. The route is POST /user and it talks to an API. check the code. The POST data works
