### ISSUE TITLE
Awesome router

### ISSUE THREAD

**Issue by osazeblogger** [phprouter/router_xss_csrf#54]
This router is very fast and simple to understand. However, it would be better to remove session_start and have it invoked only when called by the set_csrf function. Not everyone prefers to set cookies on their page, especially when some pages are cached.

**Comment by santiagodonoso** [comment]
You are right about this. I am moving the session_start to be invoked only inside the functions that need it.

**Comment by phprouter** [comment]
Great. I will move the session_start
