### ISSUE TITLE
optional params

### ISSUE THREAD

**Issue by frumbert** [phprouter/router_xss_csrf#57]
Is there any way to modify the route function to allow using an unknown number of parameters in a callback? perhaps be able to detect `*` in the route and map the remaining parameters using a variadic ?

```
get('/search/$table/*', function ($area, ...$rest) {
  echo "Search area: $area<br>";
  echo "Search rest: ";
  print_r($rest); // e.g. "age=25/name=martyn/type=intj/dnd=lg"
}
```

would match

```
    /search/entries/year/2005/month/may
    /search/users/firstname/josh
    /search/stats/age=25/name=martyn/type=intj/dnd=lg
```

would not match

```
    /search/games
```

I realise using a querystring is an alternative, e.g. `/search/stats?age=25&name=martyn&type=intj&dnd=lg` but it's not as url/seo friendly.

**Comment by phprouter** [comment]
PhpRouter does not support *
