### ISSUE TITLE
Working in cpanel, not in my PC[ubuntu]

### ISSUE THREAD

**Issue by pj8912** [phprouter/router_xss_csrf#58]
I'm using ubuntu and ran a local server in cmd `php -S localhost:4000`. This was not working.
Then I directly deployed this on my hosting which works fine. No changes in code, just the same one here.

Working in hosting, not in my local machine. Would like to know if there are any config needed to be done to be able to run on `php -S localhost`

**Comment by pj8912** [comment]
![image](https://github.com/phprouter/main/assets/59218902/45792d57-624e-4bdc-9fd7-16e927d7a76b)
![image](https://github.com/phprouter/main/assets/59218902/ead349ce-1477-4f91-9ce9-8103b37ed4cb)

**Comment by NilsSlui** [comment]
If you want to use PHP's built in web-server you can try renaming routes.php to index.php.

**Comment by pj8912** [comment]
This works thanks!!
For using this in PHPs built in server : 
- rename routes.php file to index.php
- change routes.php to index.php in .htaccess
