### ISSUE TITLE
render index and  404 always in the end

### ISSUE THREAD

**Issue by mariomeraz** [phprouter/router_xss_csrf#59]
Hello!

First of all, thank you for the work of this library, my question is the following, my index is empty, and it always redirects me to page 404, if I have it with content, it loads the content and all the way down it loads 404, it will be a problem my local server? use MAMP

![Captura de pantalla 2023-09-20 a la(s) 12 06 53 p m](https://github.com/phprouter/main/assets/14825814/24ab3a93-163b-4907-a62e-c307cff1537f)

**Comment by phprouter** [comment]
Create a route: any(). Look at the documentation in phprouter.com
