### ISSUE TITLE
.htaccess provided causes infinite loop in cloudflare

### ISSUE THREAD

**Issue by syrex1013** [phprouter/router_xss_csrf#60]
Hi,

Your router causes infinite loop in cloudflare.
Setting up just bare-bones script in cloudflare (HTTP not HTTPS server and HTTPS redirect disabled on cloudflare), it causes infinite redirect loop.

**Comment by phprouter** [comment]
Must be something in cloudfare, PhpRouter is hosted in a similar cloud provider and has no issues between redirects from HTTP to HTTPS
