### ISSUE TITLE
Query strings with multiple values

### ISSUE THREAD

**Issue by NeXxik91** [phprouter/router_xss_csrf#63]
Hey guys, this looks like a cool router, but I have a problem with query strings. I would like to use something like this?

https://url.com/id/1?status=1&color=blue&size=1,2,3&merchant=99,15,28,37,45,69

Any idea how to make this work?

**Comment by phprouter** [comment]
Create a router in "routes.php". The route:
get('/id/$id', 'views/YOUR_PHP_FILE_HERE')

The query string can be used inside YOUR_PHP_FILE as:
$_GET['color']

**Comment by NeXxik91** [comment]
Ahhh, I see. Pretty easy. I already had this, but I am using this for search queries and it collides with paramater in routerClass.php, I am idiot. Good work with this router BTW, thank you :)

$conditions[] = 'kekurzu = ?';
$parameters[] = $idaktualni;                                 

if (isset($_GET["stav"]) && !empty($_GET["stav"])) {
    $conditions[] = 'stav = ?';
    $parameters[] = $_GET["stav"];
}

if (isset($_GET["slovo"]) && !empty($_GET["slovo"])) {
    $conditions[] = 'nazev LIKE ?';
    $parameters[] = '%' . $_GET["slovo"] . '%';
}
