### ISSUE TITLE
phprouter does not work inside subfolders.

### ISSUE THREAD

**Issue by java-plus-plus** [phprouter/router_xss_csrf#9]
This was a very good library and it was all I wanted, but except that I can use it only if my project is hosted at the root folder of the server.

But I have multiple projects there and I want to use this one inside localhost/example-project folder.
That is not working since you're using DOCUMENT_ROOT everywhere, any fix?

**Comment by phprouter** [comment]
As for now you should work on your project directly under the "htdocs" folder. This means that you can work with one project at a time.
